# Generated by Django 2.0.3 on 2018-04-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('categoryId', models.CharField(max_length=20)),
                ('childId', models.CharField(max_length=30)),
            ],
        ),
    ]
